"""Update ArticleContent model with plain_text, html_text and is_fetched fields

Revision ID: 5be6487674ab
Revises: c669f81ae760
Create Date: 2025-08-20 09:00:02.575717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be6487674ab'
down_revision: Union[str, Sequence[str], None] = 'c669f81ae760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_content', sa.Column('plain_text', sa.Text(), nullable=True))
    op.add_column('article_content', sa.Column('html_text', sa.Text(), nullable=True))
    op.add_column('article_content', sa.Column('is_fetched', sa.Integer(), nullable=True))
    op.drop_column('article_content', 'content_type')
    op.drop_column('article_content', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_content', sa.Column('content', sa.TEXT(), nullable=True))
    op.add_column('article_content', sa.Column('content_type', sa.VARCHAR(), nullable=True))
    op.drop_column('article_content', 'is_fetched')
    op.drop_column('article_content', 'html_text')
    op.drop_column('article_content', 'plain_text')
    # ### end Alembic commands ###
