"""Rename feeds to sources and feed_entries to articles

Revision ID: 5c9e5dacb180
Revises: 27e919be9532
Create Date: 2025-08-19 17:10:23.179375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9e5dacb180'
down_revision: Union[str, Sequence[str], None] = '27e919be9532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feeds_id'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_slug'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_index(op.f('ix_feed_entries_id'), table_name='feed_entries')
    op.drop_index(op.f('ix_feed_entries_slug'), table_name='feed_entries')
    op.drop_table('feed_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('feed_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('link', sa.VARCHAR(), nullable=False),
    sa.Column('published_date', sa.DATETIME(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index(op.f('ix_feed_entries_slug'), 'feed_entries', ['slug'], unique=1)
    op.create_index(op.f('ix_feed_entries_id'), 'feed_entries', ['id'], unique=False)
    op.create_table('feeds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('last_fetched', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_feeds_slug'), 'feeds', ['slug'], unique=1)
    op.create_index(op.f('ix_feeds_id'), 'feeds', ['id'], unique=False)
    # ### end Alembic commands ###
