/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedSlugIndexRouteImport } from './routes/feed/$slug/index'
import { Route as FeedSlugArticleArticleSlugIndexRouteImport } from './routes/feed/$slug/article/$article-slug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugIndexRoute = FeedSlugIndexRouteImport.update({
  id: '/feed/$slug/',
  path: '/feed/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugArticleArticleSlugIndexRoute =
  FeedSlugArticleArticleSlugIndexRouteImport.update({
    id: '/feed/$slug/article/$article-slug/',
    path: '/feed/$slug/article/$article-slug/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed/$slug': typeof FeedSlugIndexRoute
  '/feed/$slug/article/$article-slug': typeof FeedSlugArticleArticleSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed/$slug': typeof FeedSlugIndexRoute
  '/feed/$slug/article/$article-slug': typeof FeedSlugArticleArticleSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed/$slug/': typeof FeedSlugIndexRoute
  '/feed/$slug/article/$article-slug/': typeof FeedSlugArticleArticleSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feed/$slug' | '/feed/$slug/article/$article-slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feed/$slug' | '/feed/$slug/article/$article-slug'
  id: '__root__' | '/' | '/feed/$slug/' | '/feed/$slug/article/$article-slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedSlugIndexRoute: typeof FeedSlugIndexRoute
  FeedSlugArticleArticleSlugIndexRoute: typeof FeedSlugArticleArticleSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug/': {
      id: '/feed/$slug/'
      path: '/feed/$slug'
      fullPath: '/feed/$slug'
      preLoaderRoute: typeof FeedSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug/article/$article-slug/': {
      id: '/feed/$slug/article/$article-slug/'
      path: '/feed/$slug/article/$article-slug'
      fullPath: '/feed/$slug/article/$article-slug'
      preLoaderRoute: typeof FeedSlugArticleArticleSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedSlugIndexRoute: FeedSlugIndexRoute,
  FeedSlugArticleArticleSlugIndexRoute: FeedSlugArticleArticleSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
